language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=2.3.1
- ALPINE_VER=3.10
- OPENSMTPD_VER=6.0.3 TAGS=6.0,6,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
