language: python

sudo: required

services:
  - docker

env:
  global:
    - LATEST_OPENSMTPD_VER=6.0.2
  matrix:
    - OPENSMTPD_VER=6.0.2

script:
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    make release

    if [[ -n "${TRAVIS_TAG}" ]]; then
      make release TAG="${OPENSMTPD_VER}-${TRAVIS_TAG}"
    fi

    if [[ "${OPENSMTPD_VER}" == "${LATEST_OPENSMTPD_VER}" ]]; then
      make release TAG="latest"
    fi
  fi
