language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=2.2.2
- ALPINE_VER=3.9
- OPENSMTPD_VER=6.0.3 TAGS=6.0,6,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"
